channels:
    - conda-forge
    - pytorch
name:
    synaptic-reconstruction
dependencies:
    - python=3.9
    - python-elf
    - napari
    - pip
    - pyqt
    - magicgui
    - pytorch
    - bioimageio.core
    - kornia
    - tensorboard
    - pdoc
    - scikit-learn
    - mrcfile
    - pip:
        - napari-skimage-regionprops
