channels:
    - pytorch
    - conda-forge
name:
    synapse-net
dependencies:
    - bioimageio.core
    - cpuonly
    - kornia
    - magicgui
    - napari
    - pip
    - pyqt
    - python-elf
    - pytorch
    - tensorboard
    - torch_em
    - trimesh
    - pip:
        - napari-skimage-regionprops
