channels:
    - conda-forge
name:
    synapse-net
dependencies:
    - bioimageio.core
    - bioimage-cpp
    - kornia
    - magicgui
    - napari >=0.7.0
    - pip
    - pyqt
    - python-elf >=0.9.0
    - pytorch
    - tabulate  # For the evaluation scripts, which print their results with pandas.to_markdown.
    - tensorboard
    - torch_em >=0.9.0
    - torchvision
    - trimesh
    - zarr <3
    - pip:
        - napari-skimage-regionprops
